//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniteGPS.Android.prd_ws.unitegps.com {
    
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="UniteGPS.Android.prd_ws.unitegps.com", ConfigurationName="IBusService")]
public interface IBusService {
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.unitegps.com/bus/10/2013) of message LogOnParentRequest does not match the default value (UniteGPS.Android.prd_ws.unitegps.com)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.unitegps.com/bus/10/2013/IBusService/LogOnParent", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/LogOnParentResponse")]
    LogOnParentResponse LogOnParent(LogOnParentRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.unitegps.com/bus/10/2013/IBusService/LogOnParent", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/LogOnParentResponse")]
    System.IAsyncResult BeginLogOnParent(LogOnParentRequest request, System.AsyncCallback callback, object asyncState);
    
    LogOnParentResponse EndLogOnParent(System.IAsyncResult result);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.unitegps.com/bus/10/2013) of message LogOnDriverRequest does not match the default value (UniteGPS.Android.prd_ws.unitegps.com)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.unitegps.com/bus/10/2013/IBusService/LogOnDriver", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/LogOnDriverResponse")]
    LogOnDriverResponse LogOnDriver(LogOnDriverRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.unitegps.com/bus/10/2013/IBusService/LogOnDriver", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/LogOnDriverResponse")]
    System.IAsyncResult BeginLogOnDriver(LogOnDriverRequest request, System.AsyncCallback callback, object asyncState);
    
    LogOnDriverResponse EndLogOnDriver(System.IAsyncResult result);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.unitegps.com/bus/10/2013) of message GetRoutesRequest does not match the default value (UniteGPS.Android.prd_ws.unitegps.com)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.unitegps.com/bus/10/2013/IBusService/GetRoutes", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/GetRoutesResponse")]
    GetRoutesResponse GetRoutes(GetRoutesRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.unitegps.com/bus/10/2013/IBusService/GetRoutes", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/GetRoutesResponse")]
    System.IAsyncResult BeginGetRoutes(GetRoutesRequest request, System.AsyncCallback callback, object asyncState);
    
    GetRoutesResponse EndGetRoutes(System.IAsyncResult result);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.unitegps.com/bus/10/2013) of message UpdateRouteRequest does not match the default value (UniteGPS.Android.prd_ws.unitegps.com)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.unitegps.com/bus/10/2013/IBusService/UpdateRoute", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/UpdateRouteResponse")]
    UpdateRouteResponse UpdateRoute(UpdateRouteRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.unitegps.com/bus/10/2013/IBusService/UpdateRoute", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/UpdateRouteResponse")]
    System.IAsyncResult BeginUpdateRoute(UpdateRouteRequest request, System.AsyncCallback callback, object asyncState);
    
    UpdateRouteResponse EndUpdateRoute(System.IAsyncResult result);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.unitegps.com/bus/10/2013) of message SaveRouteRequest does not match the default value (UniteGPS.Android.prd_ws.unitegps.com)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.unitegps.com/bus/10/2013/IBusService/SaveRoute", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/SaveRouteResponse")]
    SaveRouteResponse SaveRoute(SaveRouteRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.unitegps.com/bus/10/2013/IBusService/SaveRoute", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/SaveRouteResponse")]
    System.IAsyncResult BeginSaveRoute(SaveRouteRequest request, System.AsyncCallback callback, object asyncState);
    
    SaveRouteResponse EndSaveRoute(System.IAsyncResult result);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.unitegps.com/bus/10/2013) of message RouteExistsRequest does not match the default value (UniteGPS.Android.prd_ws.unitegps.com)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.unitegps.com/bus/10/2013/IBusService/RouteExists", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/RouteExistsResponse")]
    RouteExistsResponse RouteExists(RouteExistsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.unitegps.com/bus/10/2013/IBusService/RouteExists", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/RouteExistsResponse")]
    System.IAsyncResult BeginRouteExists(RouteExistsRequest request, System.AsyncCallback callback, object asyncState);
    
    RouteExistsResponse EndRouteExists(System.IAsyncResult result);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.unitegps.com/bus/10/2013) of message GetStopsForRouteRequest does not match the default value (UniteGPS.Android.prd_ws.unitegps.com)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.unitegps.com/bus/10/2013/IBusService/GetStopsForRoute", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/GetStopsForRouteResponse")]
    GetStopsForRouteResponse GetStopsForRoute(GetStopsForRouteRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.unitegps.com/bus/10/2013/IBusService/GetStopsForRoute", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/GetStopsForRouteResponse")]
    System.IAsyncResult BeginGetStopsForRoute(GetStopsForRouteRequest request, System.AsyncCallback callback, object asyncState);
    
    GetStopsForRouteResponse EndGetStopsForRoute(System.IAsyncResult result);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.unitegps.com/bus/10/2013) of message GetBusCoordinatesRequest does not match the default value (UniteGPS.Android.prd_ws.unitegps.com)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.unitegps.com/bus/10/2013/IBusService/GetBusCoordinates", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/GetBusCoordinatesResponse")]
    GetBusCoordinatesResponse GetBusCoordinates(GetBusCoordinatesRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.unitegps.com/bus/10/2013/IBusService/GetBusCoordinates", ReplyAction="http://www.unitegps.com/bus/10/2013/IBusService/GetBusCoordinatesResponse")]
    System.IAsyncResult BeginGetBusCoordinates(GetBusCoordinatesRequest request, System.AsyncCallback callback, object asyncState);
    
    GetBusCoordinatesResponse EndGetBusCoordinates(System.IAsyncResult result);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="LogOnParent", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class LogOnParentRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public string userName;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=1)]
    public string password;
    
    public LogOnParentRequest() {
    }
    
    public LogOnParentRequest(string userName, string password) {
        this.userName = userName;
        this.password = password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="LogOnParentResponse", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class LogOnParentResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public string LogOnParentResult;
    
    public LogOnParentResponse() {
    }
    
    public LogOnParentResponse(string LogOnParentResult) {
        this.LogOnParentResult = LogOnParentResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="LogOnDriver", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class LogOnDriverRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public string userName;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=1)]
    public string password;
    
    public LogOnDriverRequest() {
    }
    
    public LogOnDriverRequest(string userName, string password) {
        this.userName = userName;
        this.password = password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="LogOnDriverResponse", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class LogOnDriverResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public string LogOnDriverResult;
    
    public LogOnDriverResponse() {
    }
    
    public LogOnDriverResponse(string LogOnDriverResult) {
        this.LogOnDriverResult = LogOnDriverResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetRoutes", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class GetRoutesRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public int userId;
    
    public GetRoutesRequest() {
    }
    
    public GetRoutesRequest(int userId) {
        this.userId = userId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetRoutesResponse", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class GetRoutesResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public string GetRoutesResult;
    
    public GetRoutesResponse() {
    }
    
    public GetRoutesResponse(string GetRoutesResult) {
        this.GetRoutesResult = GetRoutesResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRoute", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class UpdateRouteRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public int routeId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=1)]
    public string coordinates;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=2)]
    public string newStops;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=3)]
    public int createdBy;
    
    public UpdateRouteRequest() {
    }
    
    public UpdateRouteRequest(int routeId, string coordinates, string newStops, int createdBy) {
        this.routeId = routeId;
        this.coordinates = coordinates;
        this.newStops = newStops;
        this.createdBy = createdBy;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRouteResponse", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class UpdateRouteResponse {
    
    public UpdateRouteResponse() {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SaveRoute", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class SaveRouteRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public string name;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=1)]
    public int userId;
    
    public SaveRouteRequest() {
    }
    
    public SaveRouteRequest(string name, int userId) {
        this.name = name;
        this.userId = userId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SaveRouteResponse", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class SaveRouteResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public int SaveRouteResult;
    
    public SaveRouteResponse() {
    }
    
    public SaveRouteResponse(int SaveRouteResult) {
        this.SaveRouteResult = SaveRouteResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="RouteExists", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class RouteExistsRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public string name;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=1)]
    public int userId;
    
    public RouteExistsRequest() {
    }
    
    public RouteExistsRequest(string name, int userId) {
        this.name = name;
        this.userId = userId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="RouteExistsResponse", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class RouteExistsResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public int RouteExistsResult;
    
    public RouteExistsResponse() {
    }
    
    public RouteExistsResponse(int RouteExistsResult) {
        this.RouteExistsResult = RouteExistsResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetStopsForRoute", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class GetStopsForRouteRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public int userId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=1)]
    public int routeId;
    
    public GetStopsForRouteRequest() {
    }
    
    public GetStopsForRouteRequest(int userId, int routeId) {
        this.userId = userId;
        this.routeId = routeId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetStopsForRouteResponse", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class GetStopsForRouteResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public string GetStopsForRouteResult;
    
    public GetStopsForRouteResponse() {
    }
    
    public GetStopsForRouteResponse(string GetStopsForRouteResult) {
        this.GetStopsForRouteResult = GetStopsForRouteResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetBusCoordinates", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class GetBusCoordinatesRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public int routeId;
    
    public GetBusCoordinatesRequest() {
    }
    
    public GetBusCoordinatesRequest(int routeId) {
        this.routeId = routeId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetBusCoordinatesResponse", WrapperNamespace="http://www.unitegps.com/bus/10/2013", IsWrapped=true)]
public partial class GetBusCoordinatesResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.unitegps.com/bus/10/2013", Order=0)]
    public string GetBusCoordinatesResult;
    
    public GetBusCoordinatesResponse() {
    }
    
    public GetBusCoordinatesResponse(string GetBusCoordinatesResult) {
        this.GetBusCoordinatesResult = GetBusCoordinatesResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBusServiceChannel : IBusService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BusServiceClient : System.ServiceModel.ClientBase<IBusService>, IBusService {
    
    public BusServiceClient() {
    }
    
    public BusServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public BusServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public BusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public BusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    LogOnParentResponse IBusService.LogOnParent(LogOnParentRequest request) {
        return base.Channel.LogOnParent(request);
    }
    
    public string LogOnParent(string userName, string password) {
        LogOnParentRequest inValue = new LogOnParentRequest();
        inValue.userName = userName;
        inValue.password = password;
        LogOnParentResponse retVal = ((IBusService)(this)).LogOnParent(inValue);
        return retVal.LogOnParentResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBusService.BeginLogOnParent(LogOnParentRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginLogOnParent(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginLogOnParent(string userName, string password, System.AsyncCallback callback, object asyncState) {
        LogOnParentRequest inValue = new LogOnParentRequest();
        inValue.userName = userName;
        inValue.password = password;
        return ((IBusService)(this)).BeginLogOnParent(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    LogOnParentResponse IBusService.EndLogOnParent(System.IAsyncResult result) {
        return base.Channel.EndLogOnParent(result);
    }
    
    public string EndLogOnParent(System.IAsyncResult result) {
        LogOnParentResponse retVal = ((IBusService)(this)).EndLogOnParent(result);
        return retVal.LogOnParentResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    LogOnDriverResponse IBusService.LogOnDriver(LogOnDriverRequest request) {
        return base.Channel.LogOnDriver(request);
    }
    
    public string LogOnDriver(string userName, string password) {
        LogOnDriverRequest inValue = new LogOnDriverRequest();
        inValue.userName = userName;
        inValue.password = password;
        LogOnDriverResponse retVal = ((IBusService)(this)).LogOnDriver(inValue);
        return retVal.LogOnDriverResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBusService.BeginLogOnDriver(LogOnDriverRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginLogOnDriver(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginLogOnDriver(string userName, string password, System.AsyncCallback callback, object asyncState) {
        LogOnDriverRequest inValue = new LogOnDriverRequest();
        inValue.userName = userName;
        inValue.password = password;
        return ((IBusService)(this)).BeginLogOnDriver(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    LogOnDriverResponse IBusService.EndLogOnDriver(System.IAsyncResult result) {
        return base.Channel.EndLogOnDriver(result);
    }
    
    public string EndLogOnDriver(System.IAsyncResult result) {
        LogOnDriverResponse retVal = ((IBusService)(this)).EndLogOnDriver(result);
        return retVal.LogOnDriverResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetRoutesResponse IBusService.GetRoutes(GetRoutesRequest request) {
        return base.Channel.GetRoutes(request);
    }
    
    public string GetRoutes(int userId) {
        GetRoutesRequest inValue = new GetRoutesRequest();
        inValue.userId = userId;
        GetRoutesResponse retVal = ((IBusService)(this)).GetRoutes(inValue);
        return retVal.GetRoutesResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBusService.BeginGetRoutes(GetRoutesRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginGetRoutes(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginGetRoutes(int userId, System.AsyncCallback callback, object asyncState) {
        GetRoutesRequest inValue = new GetRoutesRequest();
        inValue.userId = userId;
        return ((IBusService)(this)).BeginGetRoutes(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetRoutesResponse IBusService.EndGetRoutes(System.IAsyncResult result) {
        return base.Channel.EndGetRoutes(result);
    }
    
    public string EndGetRoutes(System.IAsyncResult result) {
        GetRoutesResponse retVal = ((IBusService)(this)).EndGetRoutes(result);
        return retVal.GetRoutesResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UpdateRouteResponse IBusService.UpdateRoute(UpdateRouteRequest request) {
        return base.Channel.UpdateRoute(request);
    }
    
    public void UpdateRoute(int routeId, string coordinates, string newStops, int createdBy) {
        UpdateRouteRequest inValue = new UpdateRouteRequest();
        inValue.routeId = routeId;
        inValue.coordinates = coordinates;
        inValue.newStops = newStops;
        inValue.createdBy = createdBy;
        UpdateRouteResponse retVal = ((IBusService)(this)).UpdateRoute(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBusService.BeginUpdateRoute(UpdateRouteRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginUpdateRoute(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginUpdateRoute(int routeId, string coordinates, string newStops, int createdBy, System.AsyncCallback callback, object asyncState) {
        UpdateRouteRequest inValue = new UpdateRouteRequest();
        inValue.routeId = routeId;
        inValue.coordinates = coordinates;
        inValue.newStops = newStops;
        inValue.createdBy = createdBy;
        return ((IBusService)(this)).BeginUpdateRoute(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UpdateRouteResponse IBusService.EndUpdateRoute(System.IAsyncResult result) {
        return base.Channel.EndUpdateRoute(result);
    }
    
    public void EndUpdateRoute(System.IAsyncResult result) {
        UpdateRouteResponse retVal = ((IBusService)(this)).EndUpdateRoute(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SaveRouteResponse IBusService.SaveRoute(SaveRouteRequest request) {
        return base.Channel.SaveRoute(request);
    }
    
    public int SaveRoute(string name, int userId) {
        SaveRouteRequest inValue = new SaveRouteRequest();
        inValue.name = name;
        inValue.userId = userId;
        SaveRouteResponse retVal = ((IBusService)(this)).SaveRoute(inValue);
        return retVal.SaveRouteResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBusService.BeginSaveRoute(SaveRouteRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginSaveRoute(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginSaveRoute(string name, int userId, System.AsyncCallback callback, object asyncState) {
        SaveRouteRequest inValue = new SaveRouteRequest();
        inValue.name = name;
        inValue.userId = userId;
        return ((IBusService)(this)).BeginSaveRoute(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SaveRouteResponse IBusService.EndSaveRoute(System.IAsyncResult result) {
        return base.Channel.EndSaveRoute(result);
    }
    
    public int EndSaveRoute(System.IAsyncResult result) {
        SaveRouteResponse retVal = ((IBusService)(this)).EndSaveRoute(result);
        return retVal.SaveRouteResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    RouteExistsResponse IBusService.RouteExists(RouteExistsRequest request) {
        return base.Channel.RouteExists(request);
    }
    
    public int RouteExists(string name, int userId) {
        RouteExistsRequest inValue = new RouteExistsRequest();
        inValue.name = name;
        inValue.userId = userId;
        RouteExistsResponse retVal = ((IBusService)(this)).RouteExists(inValue);
        return retVal.RouteExistsResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBusService.BeginRouteExists(RouteExistsRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginRouteExists(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginRouteExists(string name, int userId, System.AsyncCallback callback, object asyncState) {
        RouteExistsRequest inValue = new RouteExistsRequest();
        inValue.name = name;
        inValue.userId = userId;
        return ((IBusService)(this)).BeginRouteExists(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    RouteExistsResponse IBusService.EndRouteExists(System.IAsyncResult result) {
        return base.Channel.EndRouteExists(result);
    }
    
    public int EndRouteExists(System.IAsyncResult result) {
        RouteExistsResponse retVal = ((IBusService)(this)).EndRouteExists(result);
        return retVal.RouteExistsResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetStopsForRouteResponse IBusService.GetStopsForRoute(GetStopsForRouteRequest request) {
        return base.Channel.GetStopsForRoute(request);
    }
    
    public string GetStopsForRoute(int userId, int routeId) {
        GetStopsForRouteRequest inValue = new GetStopsForRouteRequest();
        inValue.userId = userId;
        inValue.routeId = routeId;
        GetStopsForRouteResponse retVal = ((IBusService)(this)).GetStopsForRoute(inValue);
        return retVal.GetStopsForRouteResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBusService.BeginGetStopsForRoute(GetStopsForRouteRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginGetStopsForRoute(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginGetStopsForRoute(int userId, int routeId, System.AsyncCallback callback, object asyncState) {
        GetStopsForRouteRequest inValue = new GetStopsForRouteRequest();
        inValue.userId = userId;
        inValue.routeId = routeId;
        return ((IBusService)(this)).BeginGetStopsForRoute(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetStopsForRouteResponse IBusService.EndGetStopsForRoute(System.IAsyncResult result) {
        return base.Channel.EndGetStopsForRoute(result);
    }
    
    public string EndGetStopsForRoute(System.IAsyncResult result) {
        GetStopsForRouteResponse retVal = ((IBusService)(this)).EndGetStopsForRoute(result);
        return retVal.GetStopsForRouteResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetBusCoordinatesResponse IBusService.GetBusCoordinates(GetBusCoordinatesRequest request) {
        return base.Channel.GetBusCoordinates(request);
    }
    
    public string GetBusCoordinates(int routeId) {
        GetBusCoordinatesRequest inValue = new GetBusCoordinatesRequest();
        inValue.routeId = routeId;
        GetBusCoordinatesResponse retVal = ((IBusService)(this)).GetBusCoordinates(inValue);
        return retVal.GetBusCoordinatesResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBusService.BeginGetBusCoordinates(GetBusCoordinatesRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginGetBusCoordinates(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginGetBusCoordinates(int routeId, System.AsyncCallback callback, object asyncState) {
        GetBusCoordinatesRequest inValue = new GetBusCoordinatesRequest();
        inValue.routeId = routeId;
        return ((IBusService)(this)).BeginGetBusCoordinates(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetBusCoordinatesResponse IBusService.EndGetBusCoordinates(System.IAsyncResult result) {
        return base.Channel.EndGetBusCoordinates(result);
    }
    
    public string EndGetBusCoordinates(System.IAsyncResult result) {
        GetBusCoordinatesResponse retVal = ((IBusService)(this)).EndGetBusCoordinates(result);
        return retVal.GetBusCoordinatesResult;
    }
}
